version: ~> 1.0

env:
  global:
    - secure: "erB8y/yd0SxhRWShfMj+yDiI95zhRYbVtjp/LThgRXUXLRCJLIr1zAa8VHZoy7XaY/iLDXRGnenX/dEetRbGqpSqwmMKnG3bJUhX9GZwljChGXt+Rvd6j5LmcrskYkSZAkVkaOo4tarT/Dq9OZJBbMWqZTjTBUKjtglGY2lWUFc3aSFSJMf/8BS9UYwcErXa8W8mhTeI7a6Fw/EBJEL6PQld3OeVB28MnjdgzGuPnaJhs11Ri9QBQB0dCUfPGa3zc+l4RcIjw+6Y2BtM9/1fz2Q6fbj6BZmzphrFgjilTMSuwqU/ypNib32I96cmpLKRJiEsC3nwkIfeE+Go8aoc/nIFuldUFz5y85ffjKlLba6tPdDDnQ9mZpQ4dc1Jn4baO1MHzoSlB2H95qCpph0NYjjLC8qErJNHERrS450YBynwjHP3ELBISkrQZAqm6E+6F3QrCI++Gy9C/0bcI1QxAm6QCdbyuM3oeyOlHPrEX9da39imJY6jVLh0fCjSYa5JwFPoLD8QiiFY5/V3Ij0lPJghpLfmptYyIFBb7sgGf3NEQdmw1LHRppj6kPPWvmdUXX8wTZw+5kdwkvFlJRpiwmyw/2MylRIQ/8UX7Fu1QUaO5x9Tc4HuGhAfEqJHm9TMYsrl+yxm+808yu7Rw0YFy9EmsIAHiSC95l2qBj82gcM="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="nabs"

    # The name of the conda package
    - CONDA_PACKAGE="nabs"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    - name: "Python 3.6 - PIP"
    - name: "Python 3.7"
    - name: "Python 3.8"

import:
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Python Linter
  #   - Package Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
